name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    container:
      image: ghcr.io/capsize-games/ksd-build:master
      credentials:
        username: capsize-games
        password: ${{ secrets. }}
    steps:
      - name: Build the plugin
        run: |
          bash
          cd /home/dev/ksd-build
          ./bin/linux/package --clean true --system linux --target production
